### ISSUE TITLE
The index page is cached for a year

### ISSUE THREAD

**Issue by edmorley** [andymckay/arewewebextensionsyet.com#13]
```
$ curl -I http://arewewebextensionsyet.com/
...
Last-Modified: Tue, 15 Aug 2017 00:40:03 GMT
ETag: "599242e3-c931"
Expires: Thu, 31 Dec 2037 23:55:55 GMT
Cache-Control: max-age=315360000
```

This means unless the user force reloads the page, or clears their cache, or the cache entry is evicted, they won't see the updated page for a year.

**Comment by edmorley** [comment]
@andymckay ping? :-)
This bug means that most people won't see the correct version of the page, so it would be good to fix this.

**Comment by andymckay** [comment]
Fixed, thanks.
