### ISSUE TITLE
Sync with Google Docs list

### ISSUE THREAD

**Issue by mmuman** [andymckay/arewewebextensionsyet.com#14]
Someone started a list using… [google docs](https://docs.google.com/spreadsheets/d/1TFcEXMcKrwoIAECIVyBU0GPoSmRqZ7A0VBvqeKYVSww/edit#gid=0). Still, it'd be nice to sync both lists instead of duplicating effort.

**Comment by andymckay** [comment]
My list is taken from AMO and telemetry data. Not going to manually start syncing the two unless someone wants to start sending pull requests to me :)

**Comment by mmuman** [comment]
addons-new.json seems quite manual to me, or how do you get it?
If I understand your code, I suppose you miss all the addons that don't use bugzilla.

Btw, I don't see Owl in the list, while it's been ported a week ago:
https://github.com/TigerKid001/Owl/issues/22

**Comment by mmuman** [comment]
Hmm I looked at getting the github links from the spreadsheet but instead of putting them in separate columns they used a formula so the hyperlink is stripped from the csv export :-(

**Comment by andymckay** [comment]
The list is a supplied list based on number of users from Mozilla telemetry. Owl, for example, at 2,094 users doesn't need to be tracked.

**Comment by mmuman** [comment]
Hmm, ok that's nice to Owl users… (and how is the userbase supposed to grow if it's not ported…)

Looking at the spreadsheet I see many users concerned about addons with less 10k users. Maybe you don't want to put too much data on the website but I don't see why only more known addons should be taken care of (as because they have many users they already have more chance to be taken care of actually).

**Comment by andymckay** [comment]
I'm confused why you think being on this site means anything really. It doesn't, we don't specifically "take care" of add-ons and have offered outreach to all add-on developers.

At Mozilla there are limited resources and we've offered more resources to add-ons with millions of users. Whether or not an add-on is show on this site or not is irrelevant to the add-on.

If you want to find all WebExtensions go to AMO, you'll find almost 4,000 of them: https://addons.mozilla.org/en-US/firefox/tag/firefox57

As per my first comment, I'm more than happy to accept pull request for more add-ons to add to this list.

**Comment by mmuman** [comment]
I just thought it was a place to centralize the port status for addons. But it's not more comprehensive than the man maintained google docs.

I just looked at the featured addons via the API, but less than 10 out of 250 point to github for the support_url so there's no point in trying to track those either.

I don't have the time anyway to look at addons I don't use so I'll just check the ones I need I suppose.
