### ISSUE TITLE
HTTPS Everywhere is a WebExtension

### ISSUE THREAD

**Issue by nyuszika7h** [andymckay/arewewebextensionsyet.com#15]
There is an experimental WebExtension available for HTTPS Everywhere here: https://www.eff.org/files/https-everywhere-test/index.html

Any reason it's not included?

**Comment by yfdyh000** [comment]
It is not landed on https://addons.mozilla.org/firefox/addon/https-everywhere/.

**Comment by andymckay** [comment]
As @yfdyh000 says, this data is pulled from AMO.
