### ISSUE TITLE
Valence & ADB Helper are not WebExtensions

### ISSUE THREAD

**Issue by mgol** [andymckay/arewewebextensionsyet.com#16]
To the best of my knowledge, Valence & ADB Helper are not WebExtensions. They've just been signed internally by Mozilla so they're exempt from the Firefox 57+ legacy add-ons ban.

The entries in the table for those two extensions are, therefore, incorrect.

**Comment by andymckay** [comment]
That's true. Still will work in Firefox 57+ though, so that's the important point.

**Comment by mgol** [comment]
Fair enough. I just thought that since the label was changed from "WebExtension" to "WebExtension or Beta on AMO", perhaps another change, e.g. to the text AMO itself uses, i.e. "Compatible with Firefox 57+" would be true in all cases and more to the point.
