### ISSUE TITLE
FoxyProxy WebExtension beta not available

### ISSUE THREAD

**Issue by mgol** [andymckay/arewewebextensionsyet.com#17]
From https://arewewebextensionsyet.com/:
> to find a beta version, scroll to the bottom of the extension’s listing page on AMO and click “Development Channel”

However, on the FoxyProxy page there is no "Development Channel" section at the bottom of the page:
https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-standard/
<img width="1061" alt="screen shot 2017-09-09 at 16 24 04" src="https://user-images.githubusercontent.com/1758366/30240995-66298f50-957b-11e7-9a3c-c8840ebcaf79.png">

**Comment by andymckay** [comment]
I see it there at the moment. It's going to vary though between developers when add and remove betas and when this site updates. Not sure what we can do on this.

**Comment by mgol** [comment]
I still don't see it, either when signed in and when not, either in Chrome or in Firefox. Can it depend on who looks at the site?

**Comment by andymckay** [comment]
Oh you are right. The author has disabled the beta version it seems, but the AMO API is still reporting that it has an undisabled version.

**Comment by mgol** [comment]
This is no longer relevant now that the site is discontinued.
