### ISSUE TITLE
Add Media keys support to commands API

### ISSUE THREAD

**Issue by svnpenn** [andymckay/arewewebextensionsyet.com#20]
These properties:

- MediaNextTrack
- MediaPlayPause
- MediaPrevTrack
- MediaStop

are currently only supported with Chrome and Opera:

http://developer.mozilla.org/Add-ons/WebExtensions/manifest.json/commands#Browser_compatibility

That means until Firefox implements them WebExtension keyboard shortcuts will
only work with other keys (Ctrl, Alt, A-Z, F1-F12, etc). Currently Media keys
are supported with whatever WebExtensions are replacing, see this example
Add-on:

http://addons.mozilla.org/firefox/addon/media-keys

So the soon approaching Firefox 57 is going to kill this feature if it is not
implemented soon.

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/150

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/153

**Comment by andymckay** [comment]
Bugs against the Firefox API are tracked in Bugzilla which is mentioned in http://bugzilla.mozilla.org/show_bug.cgi?id=1251795 and http://bugzilla.mozilla.org/show_bug.cgi?id=1411795.

**Comment by svnpenn** [comment]
@andymckay it is highly misleading that this page:

http://arewewebextensionsyet.com

says:

> Are we WebExtensions yet? Yes.

yet this important API is not implemented, and is in fact going to break some
add-ons.

**Comment by svnpenn** [comment]
Firefox 57 is less than a week away, with [media keys][1251795] and
[global keys][1411795] still not implemented. Until this happens, you can stop
Firefox from automatically installing updates:

~~~js
Services.prefs.setBoolPref('app.update.auto', false);
~~~

[1411795]://bugzilla.mozilla.org/show_bug.cgi?id=1411795
[1251795]://bugzilla.mozilla.org/show_bug.cgi?id=1251795

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/155

**Comment by svnpenn** [comment]
Currently the Firefox [commands API][compat] does not support
[media keys][1251795] nor [global keys][1411795].

Until these issues are fixed by Mozilla, you can use [Chromium][chrom] with the
[Streamkeys extension][stream].

[1251795]://bugzilla.mozilla.org/show_bug.cgi?id=1251795
[1411795]://bugzilla.mozilla.org/show_bug.cgi?id=1411795
[chrom]://github.com/henrypp/chromium
[compat]://developer.mozilla.org/Add-ons/WebExtensions/manifest.json/commands#Browser_compatibility
[stream]://www.streamkeys.com

**Comment by svnpenn** [comment]
Actually, it appears that media keys **are working**, just not globally. Example
"manifest.json":

~~~json
{
  "name": "wh",
  "version": "1.0.0",
  "manifest_version": 2,
  "background": {
    "scripts": ["xr.js"]
  },
  "commands": {
    "ya": {
      "suggested_key": {
        "default": "MediaPlayPause"
      }
    }
  }
}
~~~

and "xr.js":

~~~js
browser.commands.onCommand.addListener(
  zu => console.log(zu)
);
~~~

Until global is implemented:

http://bugzilla.mozilla.org/show_bug.cgi?id=1411795

the above will only work if the browser has focus, but **it does work**. If you
need global, you can use Chromium with the Streamkeys extension:

- http://github.com/henrypp/chromium
- http://www.streamkeys.com

**Comment by svnpenn** [comment]
https://github.com/svnpenn/umber/issues/27
