### ISSUE TITLE
Add global keyboard shortcut support to commands API

### ISSUE THREAD

**Issue by svnpenn** [andymckay/arewewebextensionsyet.com#21]
"global" property is currently only supported with Chrome and Opera:

http://developer.mozilla.org/Add-ons/WebExtensions/manifest.json/commands#Browser_compatibility

That means until Firefox implements `global` WebExtension keyboard shortcuts
will only work if the browser has focus:

http://developer.chrome.com/apps/commands#scope

This is very bad. Currently "global" is supported with whatever WebExtensions
are replacing, see this example Add-on:

http://addons.mozilla.org/firefox/addon/media-keys

So the soon approaching Firefox 57 is going to kill this feature if it is not
implemented soon.

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/153

**Comment by andymckay** [comment]
Bugs against the Firefox API are tracked in Bugzilla which is mentioned in http://bugzilla.mozilla.org/show_bug.cgi?id=1251795 and http://bugzilla.mozilla.org/show_bug.cgi?id=1411795.

**Comment by svnpenn** [comment]
@andymckay it is highly misleading that this page:

http://arewewebextensionsyet.com

says:

> Are we WebExtensions yet? Yes.

yet this important API is not implemented, and is in fact going to break some
add-ons.

**Comment by svnpenn** [comment]
Firefox 57 is less than a week away, with [media keys][1251795] and
[global keys][1411795] still not implemented. Until this happens, you can stop
Firefox from automatically installing updates:

~~~js
Services.prefs.setBoolPref('app.update.auto', false);
~~~

[1411795]://bugzilla.mozilla.org/show_bug.cgi?id=1411795
[1251795]://bugzilla.mozilla.org/show_bug.cgi?id=1251795

**Comment by svnpenn** [comment]
https://github.com/carlin-q-scott/browser-media-keys/issues/155

**Comment by svnpenn** [comment]
Currently the Firefox [commands API][compat] does not support
[media keys][1251795] nor [global keys][1411795].

Until these issues are fixed by Mozilla, you can use [Chromium][chrom] with the
[Streamkeys extension][stream].

[1251795]://bugzilla.mozilla.org/show_bug.cgi?id=1251795
[1411795]://bugzilla.mozilla.org/show_bug.cgi?id=1411795
[chrom]://github.com/henrypp/chromium
[compat]://developer.mozilla.org/Add-ons/WebExtensions/manifest.json/commands#Browser_compatibility
[stream]://www.streamkeys.com

**Comment by svnpenn** [comment]
https://github.com/MrAlex94/Waterfox/issues/308

**Comment by svnpenn** [comment]
https://github.com/svnpenn/umber/issues/27
