### ISSUE TITLE
Way to extract APIs used by my Chrome extension?

### ISSUE THREAD

**Issue by mlissner** [andymckay/arewewebextensionsyet.com#5]
It strikes me that you've got the code here to tell me if my Chrome extension would work on Firefox. Is there a tool for this or documentation? It'd be wonderfully helpful.

**Comment by andymckay** [comment]
https://hacks.mozilla.org/2017/08/introducing-the-extension-compatibility-tester/

**Comment by mlissner** [comment]
I'm just going to go ahead and add this to my collection of "bugs I filed that changed the world." Please don't tell me otherwise.
