### ISSUE TITLE
Web Extensions browser enthusiasm

### ISSUE THREAD

**Issue by hkdobrev** [andymckay/arewewebextensionsyet.com#6]
Hi! Thank you for creating this project!

I really like the first section of a similar project about service workers where they list browser enthusiasm and current status or future plans - https://jakearchibald.github.io/isserviceworkerready/

Do you think you could include such a section in the website? I couldn't find much information about browser support other than Firefox and Chrome. Opera should support them as well and I'm particularly interested in Safari. Do you have any information for more browsers? Do you think you could add it to the website?

Thanks!

**Comment by yfdyh000** [comment]
https://github.com/mdn/browser-compat-data/tree/master/webextensions

**Comment by andymckay** [comment]
Please also see https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs, because of the quality of documentation this site is in the process of winding down.
